//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;

using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : ReviewHogMain
	/// Data Source    : reviewhog.database.windows.net
	/// Server Version : 12.00.5230
	/// </summary>
	public partial class ReviewHogMainDB : LinqToDB.Data.DataConnection
	{
		public ITable<sys_DatabaseFirewallRule> DatabaseFirewallRules { get { return this.GetTable<sys_DatabaseFirewallRule>(); } }
		public ITable<ProductDetail>            ProductDetails        { get { return this.GetTable<ProductDetail>(); } }
		public ITable<ProductEntity>            ProductEntities       { get { return this.GetTable<ProductEntity>(); } }
		public ITable<ProductReview>            ProductReviews        { get { return this.GetTable<ProductReview>(); } }
		public ITable<ProductSentiment>         ProductSentiments     { get { return this.GetTable<ProductSentiment>(); } }
		public ITable<ReviewSentimental>        ReviewSentimentals    { get { return this.GetTable<ReviewSentimental>(); } }
		public ITable<Supermarket>              Supermarkets          { get { return this.GetTable<Supermarket>(); } }
		public ITable<Sysdiagram>               Sysdiagrams           { get { return this.GetTable<Sysdiagram>(); } }

		public ReviewHogMainDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ReviewHogMainDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ReviewHogMainDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="sys", Name="database_firewall_rules", IsView=true)]
	public partial class sys_DatabaseFirewallRule
	{
		[Column("id"),               Identity] public int      Id             { get; set; } // int
		[Column("name"),             NotNull ] public string   Name           { get; set; } // nvarchar(128)
		[Column("start_ip_address"), NotNull ] public string   StartIpAddress { get; set; } // varchar(45)
		[Column("end_ip_address"),   NotNull ] public string   EndIpAddress   { get; set; } // varchar(45)
		[Column("create_date"),      NotNull ] public DateTime CreateDate     { get; set; } // datetime
		[Column("modify_date"),      NotNull ] public DateTime ModifyDate     { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="product_detail")]
	public partial class ProductDetail
	{
		[Column("id"),                 PrimaryKey,  NotNull] public long     Id               { get; set; } // bigint
		[Column("product_mapping_id"),              NotNull] public long     ProductMappingId { get; set; } // bigint
		[Column("name"),                            NotNull] public string   Name             { get; set; } // nvarchar(100)
		[Column("upc"),                   Nullable         ] public string   Upc              { get; set; } // nvarchar(50)
		[Column("brand_name"),            Nullable         ] public string   BrandName        { get; set; } // nvarchar(250)
		[Column("supermarket_id"),                  NotNull] public long     SupermarketId    { get; set; } // bigint
		[Column("star_rating_score"),     Nullable         ] public decimal? StarRatingScore  { get; set; } // decimal(3, 1)
		[Column("total_star_ratings"),    Nullable         ] public decimal? TotalStarRatings { get; set; } // numeric(18, 0)

		#region Associations

		/// <summary>
		/// FK__product_e__produ__03F0984C_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ProductEntity> Producteprodu03F0984C { get; set; }

		/// <summary>
		/// FK_product_review_product_detail_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ProductReview> Productreviewproductdetails { get; set; }

		/// <summary>
		/// FK_review_sentimental_product_detail_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ReviewSentimental> Reviewsentimentalproductdetails { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="product_entities")]
	public partial class ProductEntity
	{
		[Column("id"),                   NotNull    ] public long   Id                 { get; set; } // bigint
		[Column("product_id"),           NotNull    ] public long   ProductId          { get; set; } // bigint
		[Column("entity_name"),          NotNull    ] public string EntityName         { get; set; } // nvarchar(250)
		[Column("entity_avg_sentiment"), NotNull    ] public float  EntityAvgSentiment { get; set; } // real
		[Column("hit_count"),               Nullable] public long?  HitCount           { get; set; } // bigint

		#region Associations

		/// <summary>
		/// FK__product_e__produ__03F0984C
		/// </summary>
		[Association(ThisKey="ProductId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK__product_e__produ__03F0984C", BackReferenceName="Producteprodu03F0984C")]
		public ProductDetail Product { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="product_review")]
	public partial class ProductReview
	{
		[Column("id"),                PrimaryKey,  NotNull] public long      Id               { get; set; } // bigint
		[Column("product_id"),           Nullable         ] public long?     ProductId        { get; set; } // bigint
		[Column("review_text"),          Nullable         ] public string    ReviewText       { get; set; } // nvarchar(max)
		[Column("reviewer_name"),        Nullable         ] public string    ReviewerName     { get; set; } // nvarchar(50)
		[Column("reviewer_location"),    Nullable         ] public string    ReviewerLocation { get; set; } // nvarchar(50)
		[Column("review_date"),          Nullable         ] public DateTime? ReviewDate       { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_product_review_product_detail
		/// </summary>
		[Association(ThisKey="ProductId", OtherKey="Id", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_product_review_product_detail", BackReferenceName="Productreviewproductdetails")]
		public ProductDetail Product { get; set; }

		/// <summary>
		/// FK__review_se__revie__01142BA1_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ReviewId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ReviewSentimental> Reviewserevie01142Bas { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="product_sentiments")]
	public partial class ProductSentiment
	{
		[Column("id"),                  PrimaryKey,  NotNull] public long   Id                { get; set; } // bigint
		[Column("rating_score_avg"),       Nullable         ] public float? RatingScoreAvg    { get; set; } // real
		[Column("rating_count"),           Nullable         ] public long?  RatingCount       { get; set; } // bigint
		[Column("sentiment_score_avg"),    Nullable         ] public float? SentimentScoreAvg { get; set; } // real
		[Column("sentiment"),              Nullable         ] public string Sentiment         { get; set; } // nvarchar(20)
		[Column("product_mapping_id"),               NotNull] public long   ProductMappingId  { get; set; } // bigint
	}

	[Table(Schema="dbo", Name="review_sentimental")]
	public partial class ReviewSentimental
	{
		[Column("id"),              PrimaryKey,  NotNull] public long  Id             { get; set; } // bigint
		[Column("product_id"),         Nullable         ] public long? ProductId      { get; set; } // bigint
		[Column("review_id"),                    NotNull] public long  ReviewId       { get; set; } // bigint
		[Column("sentiment_score"),              NotNull] public float SentimentScore { get; set; } // real

		#region Associations

		/// <summary>
		/// FK_review_sentimental_product_detail
		/// </summary>
		[Association(ThisKey="ProductId", OtherKey="Id", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_review_sentimental_product_detail", BackReferenceName="Reviewsentimentalproductdetails")]
		public ProductDetail Product { get; set; }

		/// <summary>
		/// FK__review_se__revie__01142BA1
		/// </summary>
		[Association(ThisKey="ReviewId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK__review_se__revie__01142BA1", BackReferenceName="Reviewserevie01142Bas")]
		public ProductReview Review { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="supermarket")]
	public partial class Supermarket
	{
		[Column("id"),               PrimaryKey,  NotNull] public int    Id              { get; set; } // int
		[Column("supermarket_name"),    Nullable         ] public string SupermarketName { get; set; } // nvarchar(50)
	}

	[Table(Schema="dbo", Name="sysdiagrams")]
	public partial class Sysdiagram
	{
		[Column("name"),         NotNull              ] public string Name        { get; set; } // nvarchar(128)
		[Column("principal_id"), NotNull              ] public int    PrincipalId { get; set; } // int
		[Column("diagram_id"),   PrimaryKey,  Identity] public int    DiagramId   { get; set; } // int
		[Column("version"),         Nullable          ] public int?   Version     { get; set; } // int
		[Column("definition"),      Nullable          ] public byte[] Definition  { get; set; } // varbinary(max)
	}

	public static partial class ReviewHogMainDBStoredProcedures
	{
		#region SpAlterdiagram

		public static int SpAlterdiagram(this ReviewHogMainDB dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_alterdiagram]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary));
		}

		#endregion

		#region SpCreatediagram

		public static int SpCreatediagram(this ReviewHogMainDB dataConnection, string @diagramname, int? @owner_id, int? @version, byte[] @definition)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_creatediagram]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32),
				new DataParameter("@version",     @version,     LinqToDB.DataType.Int32),
				new DataParameter("@definition",  @definition,  LinqToDB.DataType.VarBinary));
		}

		#endregion

		#region SpDropdiagram

		public static int SpDropdiagram(this ReviewHogMainDB dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_dropdiagram]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32));
		}

		#endregion

		#region SpHelpdiagramdefinition

		public static IEnumerable<SpHelpdiagramdefinitionResult> SpHelpdiagramdefinition(this ReviewHogMainDB dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.QueryProc<SpHelpdiagramdefinitionResult>("[dbo].[sp_helpdiagramdefinition]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32));
		}

		public partial class SpHelpdiagramdefinitionResult
		{
			public int?   version    { get; set; }
			public byte[] definition { get; set; }
		}

		#endregion

		#region SpHelpdiagrams

		public static IEnumerable<SpHelpdiagramsResult> SpHelpdiagrams(this ReviewHogMainDB dataConnection, string @diagramname, int? @owner_id)
		{
			return dataConnection.QueryProc<SpHelpdiagramsResult>("[dbo].[sp_helpdiagrams]",
				new DataParameter("@diagramname", @diagramname, LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",    @owner_id,    LinqToDB.DataType.Int32));
		}

		public partial class SpHelpdiagramsResult
		{
			public string Database { get; set; }
			public string Name     { get; set; }
			public int    ID       { get; set; }
			public string Owner    { get; set; }
			public int    OwnerID  { get; set; }
		}

		#endregion

		#region SpRenamediagram

		public static int SpRenamediagram(this ReviewHogMainDB dataConnection, string @diagramname, int? @owner_id, string @new_diagramname)
		{
			return dataConnection.ExecuteProc("[dbo].[sp_renamediagram]",
				new DataParameter("@diagramname",     @diagramname,     LinqToDB.DataType.NVarChar),
				new DataParameter("@owner_id",        @owner_id,        LinqToDB.DataType.Int32),
				new DataParameter("@new_diagramname", @new_diagramname, LinqToDB.DataType.NVarChar));
		}

		#endregion
	}

	public static partial class SqlFunctions
	{
		#region FnDiagramobjects

		[Sql.Function(Name="dbo.fn_diagramobjects", ServerSideOnly=true)]
		public static int? FnDiagramobjects()
		{
			throw new InvalidOperationException();
		}

		#endregion
	}

	public static partial class TableExtensions
	{
		public static ProductDetail Find(this ITable<ProductDetail> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ProductReview Find(this ITable<ProductReview> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ProductSentiment Find(this ITable<ProductSentiment> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ReviewSentimental Find(this ITable<ReviewSentimental> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Supermarket Find(this ITable<Supermarket> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Sysdiagram Find(this ITable<Sysdiagram> table, int DiagramId)
		{
			return table.FirstOrDefault(t =>
				t.DiagramId == DiagramId);
		}
	}
}

#pragma warning restore 1591
