//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : ReviewHogMain
	/// Data Source    : reviewhog.database.windows.net
	/// Server Version : 12.00.5230
	/// </summary>
	public partial class ReviewHogMainDB : LinqToDB.Data.DataConnection
	{
		public ITable<DatabaseFirewallRule> DatabaseFirewallRules { get { return this.GetTable<DatabaseFirewallRule>(); } }
		public ITable<ProductDetail>        ProductDetails        { get { return this.GetTable<ProductDetail>(); } }
		public ITable<ProductReview>        ProductReviews        { get { return this.GetTable<ProductReview>(); } }
		public ITable<ReviewSentimental>    ReviewSentimentals    { get { return this.GetTable<ReviewSentimental>(); } }
		public ITable<Supermarket>          Supermarkets          { get { return this.GetTable<Supermarket>(); } }

		public ReviewHogMainDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ReviewHogMainDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public ReviewHogMainDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="sys", Name="database_firewall_rules", IsView=true)]
	public partial class DatabaseFirewallRule
	{
		[Column("id"),               Identity] public int      Id             { get; set; } // int
		[Column("name"),             NotNull ] public string   Name           { get; set; } // nvarchar(128)
		[Column("start_ip_address"), NotNull ] public string   StartIpAddress { get; set; } // varchar(45)
		[Column("end_ip_address"),   NotNull ] public string   EndIpAddress   { get; set; } // varchar(45)
		[Column("create_date"),      NotNull ] public DateTime CreateDate     { get; set; } // datetime
		[Column("modify_date"),      NotNull ] public DateTime ModifyDate     { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="product_detail")]
	public partial class ProductDetail
	{
		[Column("id"),                 PrimaryKey,  NotNull] public long     Id               { get; set; } // bigint
		[Column("product_mapping_id"),              NotNull] public long     ProductMappingId { get; set; } // bigint
		[Column("name"),                            NotNull] public string   Name             { get; set; } // nvarchar(100)
		[Column("upc"),                   Nullable         ] public string   Upc              { get; set; } // nvarchar(50)
		[Column("brand_name"),            Nullable         ] public string   BrandName        { get; set; } // nvarchar(250)
		[Column("supermarket_id"),                  NotNull] public long     SupermarketId    { get; set; } // bigint
		[Column("star_rating_score"),     Nullable         ] public decimal? StarRatingScore  { get; set; } // decimal(3, 1)
		[Column("total_star_ratings"),    Nullable         ] public decimal? TotalStarRatings { get; set; } // numeric(18, 0)

		#region Associations

		/// <summary>
		/// FK_product_review_product_detail_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ProductReview> Productreviewproductdetails { get; set; }

		/// <summary>
		/// FK_review_sentimental_product_detail_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ProductId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ReviewSentimental> Reviewsentimentalproductdetails { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="product_review")]
	public partial class ProductReview
	{
		[Column("id"),                PrimaryKey,  NotNull] public long      Id               { get; set; } // bigint
		[Column("product_id"),           Nullable         ] public long?     ProductId        { get; set; } // bigint
		[Column("review_text"),          Nullable         ] public string    ReviewText       { get; set; } // nvarchar(max)
		[Column("reviewer_name"),        Nullable         ] public string    ReviewerName     { get; set; } // nvarchar(50)
		[Column("reviewer_location"),    Nullable         ] public string    ReviewerLocation { get; set; } // nvarchar(50)
		[Column("review_date"),          Nullable         ] public DateTime? ReviewDate       { get; set; } // datetime

		#region Associations

		/// <summary>
		/// FK_product_review_product_detail
		/// </summary>
		[Association(ThisKey="ProductId", OtherKey="Id", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_product_review_product_detail", BackReferenceName="Productreviewproductdetails")]
		public ProductDetail Product { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="review_sentimental")]
	public partial class ReviewSentimental
	{
		[Column("id"),                PrimaryKey,  NotNull] public long   Id               { get; set; } // bigint
		[Column("product_id"),           Nullable         ] public long?  ProductId        { get; set; } // bigint
		[Column("review_keywords"),      Nullable         ] public string ReviewKeywords   { get; set; } // nvarchar(max)
		[Column("positive_keywords"),    Nullable         ] public string PositiveKeywords { get; set; } // nvarchar(50)
		[Column("negative_keywords"),    Nullable         ] public string NegativeKeywords { get; set; } // nvarchar(50)

		#region Associations

		/// <summary>
		/// FK_review_sentimental_product_detail
		/// </summary>
		[Association(ThisKey="ProductId", OtherKey="Id", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_review_sentimental_product_detail", BackReferenceName="Reviewsentimentalproductdetails")]
		public ProductDetail Product { get; set; }

		#endregion
	}

	[Table(Schema="dbo", Name="supermarket")]
	public partial class Supermarket
	{
		[Column("id"),               PrimaryKey,  NotNull] public int    Id              { get; set; } // int
		[Column("supermarket_name"),    Nullable         ] public string SupermarketName { get; set; } // nvarchar(50)
	}

	public static partial class TableExtensions
	{
		public static ProductDetail Find(this ITable<ProductDetail> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ProductReview Find(this ITable<ProductReview> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static ReviewSentimental Find(this ITable<ReviewSentimental> table, long Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Supermarket Find(this ITable<Supermarket> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
